language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libgnutls28-dev
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script:
  - py.test
  - coverage run --source=osmcha -m py.test
after_success:
  - coveralls
sudo: false
notifications:
  email: false
